export const CURRENCIES = [
  {
    country: "Euro area countries",
    currency: "Euro",
    currencyCode: "EUR",
    symbol: "€",
  },
  {
    country: "Albania",
    currency: "Albanian lek",
    currencyCode: "ALL",
    symbol: "L",
  },
  {
    country: "Belarus",
    currency: "Belarusian ruble",
    currencyCode: "BYN",
    symbol: "Br",
  },
  {
    country: "Bosnia and Herzegovina",
    currency: "Bosnia and Herzegovina convertible mark",
    currencyCode: "BAM",
    symbol: "KM",
  },
  {
    country: "Bulgaria",
    currency: "Bulgarian lev",
    currencyCode: "BGN",
    symbol: "лв",
  },
  {
    country: "Croatia",
    currency: "Croatian kuna",
    currencyCode: "HRK",
    symbol: "kn",
  },
  {
    country: "Czechia",
    currency: "Czech koruna",
    currencyCode: "CZK",
    symbol: "Kč",
  },
  {
    country: "Denmark",
    currency: "Danish krone",
    currencyCode: "DKK",
    symbol: "kr",
  },
  {
    country: "Georgia",
    currency: "Georgian lari",
    currencyCode: "GEL",
    symbol: "₾",
  },
  {
    country: "Greenland",
    currency: "Danish krone",
    currencyCode: "DKK",
    symbol: "kr",
  },
  {
    country: "Hungary",
    currency: "Hungarian forint",
    currencyCode: "HUF",
    symbol: "ft",
  },
  {
    country: "Iceland",
    currency: "Icelandic króna",
    currencyCode: "ISK",
    symbol: "kr",
  },
  {
    country: "Liechtenstein",
    currency: "Swiss franc",
    currencyCode: "CHF",
    symbol: "CHF",
  },
  {
    country: "Moldova",
    currency: "Moldovan leu",
    currencyCode: "MDL",
    symbol: "L",
  },
  {
    country: "North Macedonia",
    currency: "Second Macedonian denar",
    currencyCode: "MKD",
    symbol: "ден",
  },
  {
    country: "Norway",
    currency: "Norwegian krone",
    currencyCode: "NOK",
    symbol: "kr",
  },
  {
    country: "Poland",
    currency: "Polish zloty",
    currencyCode: "PLN",
    symbol: "zł",
  },
  {
    country: "Romania",
    currency: "Romanian leu",
    currencyCode: "RON",
    symbol: "lei",
  },
  {
    country: "Russia",
    currency: "Russian ruble",
    currencyCode: "RUB",
    symbol: "₽",
  },
  {
    country: "Serbia",
    currency: "Serbian dinar",
    currencyCode: "RSD",
    symbol: "RSD",
  },
  {
    country: "Sweden",
    currency: "Swedish krona",
    currencyCode: "SEK",
    symbol: "kr",
  },
  {
    country: "Switzerland",
    currency: "Swiss franc",
    currencyCode: "CHF",
    symbol: "CHF",
  },
  {
    country: "Turkey",
    currency: "Turkish lira",
    currencyCode: "TRY",
    symbol: "₺",
  },
  {
    country: "Ukraine",
    currency: "Ukrainian hryvna",
    currencyCode: "UAH",
    symbol: "₴",
  },
  {
    country: "United Kingdom",
    currency: "Pounds sterling",
    currencyCode: "GBP",
    symbol: "£",
  },
  {
    country: "United States",
    currency: "United States Dollar",
    currencyCode: "USD",
    symbol: "$",
  },
  {
    country: "OECS countries",
    currency: "East Caribbean dollar",
    currencyCode: "XCD",
    symbol: "$",
  },
  {
    country: "Aruba",
    currency: "Aruban florin",
    currencyCode: "AWG",
    symbol: "ƒ",
  },
  {
    country: "Argentina",
    currency: "Argentine peso",
    currencyCode: "ARS",
    symbol: "$",
  },
  {
    country: "The Bahamas",
    currency: "Bahamian dollar",
    currencyCode: "BSD",
    symbol: "B$",
  },
  {
    country: "Barbados",
    currency: "Barbadian dollar",
    currencyCode: "BBD",
    symbol: "$",
  },
  {
    country: "Bermuda",
    currency: "Bermudian dollar",
    currencyCode: "BMD",
    symbol: "$",
  },
  {
    country: "Belize",
    currency: "Belize dollar",
    currencyCode: "BZD",
    symbol: "BZ$",
  },
  {
    country: "Bolivia",
    currency: "Bolivian boliviano",
    currencyCode: "BOB",
    symbol: "Bs",
  },
  {
    country: "Brazil",
    currency: "Brazilian real",
    currencyCode: "BRL",
    symbol: "R$",
  },
  {
    country: "Canada",
    currency: "Canadian dollar",
    currencyCode: "CAD",
    symbol: "CA$",
  },
  {
    country: "Cayman Islands",
    currency: "Cayman Islands dollar",
    currencyCode: "KYD",
    symbol: "CI$",
  },
  {
    country: "Chile",
    currency: "Chilean peso",
    currencyCode: "CLP",
    symbol: "$",
  },
  {
    country: "Colombia",
    currency: "Colombian peso",
    currencyCode: "COP",
    symbol: "$",
  },
  {
    country: "Costa Rica",
    currency: "Costa Rican colón",
    currencyCode: "CRC",
    symbol: "₡",
  },
  {
    country: "Cuba",
    currency: "Cuban peso",
    currencyCode: "CUP",
    symbol: "CUC$",
  },
  {
    country: "Curaçao",
    currency: "Netherlands Antillean guilder",
    currencyCode: "ANG",
    symbol: "ƒ",
  },
  {
    country: "Dominican Republic",
    currency: "Dominican peso",
    currencyCode: "DOP",
    symbol: "RD$",
  },
  {
    country: "Falkland Islands",
    currency: "Falkland Islands pound",
    currencyCode: "FKP",
    symbol: "FK£",
  },
  {
    country: "Guatemala",
    currency: "Guatemalan quetzal",
    currencyCode: "GTQ",
    symbol: "Q",
  },
  {
    country: "Guyana",
    currency: "Guyanese dollar",
    currencyCode: "GYD",
    symbol: "G$",
  },
  {
    country: "Haiti",
    currency: "Haitian gourde",
    currencyCode: "HTG",
    symbol: "G",
  },
  {
    country: "Honduras",
    currency: "Honduran lempira",
    currencyCode: "HNL",
    symbol: "L",
  },
  {
    country: "Jamaica",
    currency: "Jamaican dollar",
    currencyCode: "JMD",
    symbol: "J$",
  },
  {
    country: "Mexico",
    currency: "Mexican peso",
    currencyCode: "MXN",
    symbol: "$",
  },
  {
    country: "Nicaragua",
    currency: "Nicaraguan córdoba",
    currencyCode: "NIO",
    symbol: "C$",
  },
  {
    country: "Panama",
    currency: "Panamanian balboa",
    currencyCode: "PAB",
    symbol: "B/.",
  },
  {
    country: "Paraguay",
    currency: "Paraguayan guaraní",
    currencyCode: "PYG",
    symbol: "₲",
  },
  {
    country: "Peru",
    currency: "Peruvian sol",
    currencyCode: "PEN",
    symbol: "S/.",
  },
  {
    country: "Sint Maarten",
    currency: "Netherlands Antillean guilder",
    currencyCode: "ANG",
    symbol: "ƒ",
  },
  {
    country: "Suriname",
    currency: "Surinamese dollar",
    currencyCode: "SRD",
    symbol: "Sr$",
  },
  {
    country: "Trinidad and Tobago",
    currency: "Trinidad and Tobago dollar",
    currencyCode: "TTD",
    symbol: "TT$",
  },
  {
    country: "Uruguay",
    currency: "Uruguayan peso",
    currencyCode: "UYU",
    symbol: "$U",
  },
  {
    country: "Venezuela",
    currency: "Venezuelan bolívar",
    currencyCode: "VED",
    symbol: "Bs.",
  },
  {
    country: "Afghanistan",
    currency: "Afghan afghani",
    currencyCode: "AFN",
    symbol: "؋",
  },
  {
    country: "Armenia",
    currency: "Armenian dram",
    currencyCode: "AMD",
    symbol: "֏",
  },
  {
    country: "Azerbaijan",
    currency: "Azerbaijani manat",
    currencyCode: "AZN",
    symbol: "₼",
  },
  {
    country: "Bahrain",
    currency: "Bahraini dinar",
    currencyCode: "BHD",
    symbol: ".د.ب",
  },
  {
    country: "Cyprus",
    currency: "Euro",
    currencyCode: "EUR",
    symbol: "€",
  },
  {
    country: "Iraq",
    currency: "Iraqi dinar",
    currencyCode: "IQD",
    symbol: "ع.د",
  },
  {
    country: "Iran",
    currency: "Iranian rial",
    currencyCode: "IRR",
    symbol: "﷼",
  },
  {
    country: "Israel",
    currency: "Israeli new shekel",
    currencyCode: "ILS",
    symbol: "₪",
  },
  {
    country: "Jordan",
    currency: "Jordanian dinar",
    currencyCode: "JOD",
    symbol: "ينار",
  },
  {
    country: "Kuwait",
    currency: "Kuwaiti dinar",
    currencyCode: "KWD",
    symbol: "ك",
  },
  {
    country: "Lebanon",
    currency: "Lebanese pound",
    currencyCode: "LBP",
    symbol: "ل.ل",
  },
  {
    country: "Palestine",
    currency: "Israeli shekel",
    currencyCode: "ILS",
    symbol: "₪",
  },
  {
    country: "Syria",
    currency: "Syrian pound",
    currencyCode: "SYP",
    symbol: "£S",
  },
  {
    country: "United Arab Emirates",
    currency: "Emirati dirham",
    currencyCode: "AED",
    symbol: "AED",
  },
  {
    country: "Oman",
    currency: "Omani rial",
    currencyCode: "OMR",
    symbol: "ر.ع",
  },
  {
    country: "Qatar",
    currency: "Qatari riyal",
    currencyCode: "QAR",
    symbol: "ر.ق",
  },
  {
    country: "Saudi Arabia",
    currency: "Saudi riyal",
    currencyCode: "SAR",
    symbol: "SR",
  },
  {
    country: "Yemen",
    currency: "Yemeni rial",
    currencyCode: "YER",
    symbol: "﷼",
  },
  {
    country: "West Africa",
    currency: "CFA franc",
    currencyCode: "XAF",
    symbol: "FCFA",
  },
  {
    country: "Central Africa",
    currency: "CFA franc",
    currencyCode: "XOF",
    symbol: "CFA",
  },
  {
    country: "Algeria",
    currency: "Algerian dinar",
    currencyCode: "DZD",
    symbol: "دج",
  },
  {
    country: "Angola",
    currency: "Angolan kwanza",
    currencyCode: "AOA",
    symbol: "Kz",
  },
  {
    country: "Botswana",
    currency: "Botswana pula",
    currencyCode: "BWP",
    symbol: "P",
  },
  {
    country: "Burundi",
    currency: "Burundian franc",
    currencyCode: "BIF",
    symbol: "FBu",
  },
  {
    country: "Cabo Verde",
    currency: "Cape Verdean escudo",
    currencyCode: "CVE",
    symbol: "CVE",
  },
  {
    country: "Comoros",
    currency: "Comorian franc",
    currencyCode: "KMF",
    symbol: "CF",
  },
  {
    country: "Democratic Republic of the Congo",
    currency: "Congolese franc",
    currencyCode: "CDF",
    symbol: "FC",
  },
  {
    country: "Djibouti",
    currency: "Djiboutian franc",
    currencyCode: "DJF",
    symbol: "Fdj",
  },
  {
    country: "Egypt",
    currency: "Egyptian pound",
    currencyCode: "EGP",
    symbol: "E£",
  },
  {
    country: "Eritrea",
    currency: "Eritrean nakfa",
    currencyCode: "ERN",
    symbol: "Nkf",
  },
  {
    country: "Ethiopia",
    currency: "Ethiopian birr",
    currencyCode: "ETB",
    symbol: "Br",
  },
  {
    country: "Eswatini",
    currency: "Lilangeni",
    currencyCode: "SZL",
    symbol: "L",
  },
  {
    country: "Gambia",
    currency: "Dalasi",
    currencyCode: "GMD",
    symbol: "D",
  },
  {
    country: "Ghana",
    currency: "Ghanaian cedi",
    currencyCode: "GHS",
    symbol: "GH₵",
  },
  {
    country: "Guinea",
    currency: "Guinean franc",
    currencyCode: "GNF",
    symbol: "FG",
  },
  {
    country: "Kenya",
    currency: "Kenyan shilling",
    currencyCode: "KES",
    symbol: "KSh",
  },
  {
    country: "Lesotho",
    currency: "Lesotho loti",
    currencyCode: "LSL",
    symbol: "L",
  },
  {
    country: "Liberia",
    currency: "Liberian dollar",
    currencyCode: "LRD",
    symbol: "LD$",
  },
  {
    country: "Libya",
    currency: "Libyan dinar",
    currencyCode: "LYD",
    symbol: "LD",
  },
  {
    country: "Madagascar",
    currency: "Malagasy ariary",
    currencyCode: "MGA",
    symbol: "Ar",
  },
  {
    country: "Malawi",
    currency: "Malawian kwacha",
    currencyCode: "MWK",
    symbol: "K",
  },
  {
    country: "Mauritius",
    currency: "Mauritian rupee",
    currencyCode: "MUR",
    symbol: "₨",
  },
  {
    country: "Mauritania",
    currency: "Ouguiya",
    currencyCode: "MRU",
    symbol: "UM",
  },
  {
    country: "Morocco",
    currency: "Moroccan dirham",
    currencyCode: "MAD",
    symbol: "DH",
  },
  {
    country: "Mozambique",
    currency: "Mozambican metical",
    currencyCode: "MZN",
    symbol: "MT",
  },
  {
    country: "Namibia",
    currency: "Namibian dollar",
    currencyCode: "NAD",
    symbol: "N$",
  },
  {
    country: "Nigeria",
    currency: "Nigerian naira",
    currencyCode: "NGN",
    symbol: "₦",
  },
  {
    country: "Rwanda",
    currency: "Rwandan franc",
    currencyCode: "RWF",
    symbol: "R₣",
  },
  {
    country: "Sao Tome and Principe",
    currency: "São Tomé and Príncipe dobra",
    currencyCode: "STN",
    symbol: "Db",
  },
  {
    country: "Seychelles",
    currency: "Seychellois rupee",
    currencyCode: "SCR",
    symbol: "SR",
  },
  {
    country: "Sierra Leone",
    currency: "Sierra Leonean leone",
    currencyCode: "SLL",
    symbol: "Le",
  },
  {
    country: "Somalia",
    currency: "Somali shilling",
    currencyCode: "SOS",
    symbol: "Sh.So.",
  },
  {
    country: "South Africa",
    currency: "South African rand",
    currencyCode: "ZAR",
    symbol: "R",
  },
  {
    country: "South Sudan",
    currency: "South Sudanese pound",
    currencyCode: "SSP",
    symbol: "SS£",
  },
  {
    country: "Sudan",
    currency: "Sudanese pound",
    currencyCode: "SDG",
    symbol: "SDG",
  },
  {
    country: "Tanzania",
    currency: "Tanzanian shilling",
    currencyCode: "TZS",
    symbol: "TSh",
  },
  {
    country: "Tunisia",
    currency: "Tunisian dinar",
    currencyCode: "TND",
    symbol: "د.ت",
  },
  {
    country: "Uganda",
    currency: "Ugandan shilling",
    currencyCode: "UGX",
    symbol: "USh",
  },
  {
    country: "Zimbabwe",
    currency: "United States Dollar",
    currencyCode: "USD",
    symbol: "$",
  },
  {
    country: "Australia",
    currency: "Australian dollar",
    currencyCode: "AUD",
    symbol: "A$",
  },
  {
    country: "Bangladesh",
    currency: "Bangladeshi taka",
    currencyCode: "BDT",
    symbol: "৳",
  },
  {
    country: "Bhutan",
    currency: "Bhutanese ngultrum",
    currencyCode: "BTN",
    symbol: "Nu",
  },
  {
    country: "Brunei",
    currency: "Brunei dollar",
    currencyCode: "BND",
    symbol: "B$",
  },
  {
    country: "Cambodia",
    currency: "Cambodian riel",
    currencyCode: "KHR",
    symbol: "៛",
  },
  {
    country: "China",
    currency: "Chinese yuan",
    currencyCode: "CNY",
    symbol: "¥",
  },
  {
    country: "Hong Kong",
    currency: "Hong Kong dollar",
    currencyCode: "HKD",
    symbol: "HK$",
  },
  {
    country: "Indonesia",
    currency: "Indonesian rupiah",
    currencyCode: "IDR",
    symbol: "Rp",
  },
  {
    country: "India",
    currency: "Indian rupee",
    currencyCode: "INR",
    symbol: "₹",
  },
  {
    country: "Japan",
    currency: "Japanese yen",
    currencyCode: "JPY",
    symbol: "¥",
  },
  {
    country: "Kazakhstan",
    currency: "Kazakhstani tenge",
    currencyCode: "KZT",
    symbol: "₸",
  },
  {
    country: "Kyrgyzstan",
    currency: "Kyrgyzstani som",
    currencyCode: "KGS",
    symbol: "som",
  },
  {
    country: "Laos",
    currency: "Lao kip",
    currencyCode: "LAK",
    symbol: "₭",
  },
  {
    country: "Macau",
    currency: "Macanese pataca",
    currencyCode: "MOP",
    symbol: "MOP$",
  },
  {
    country: "Malaysia",
    currency: "Malaysian ringgit",
    currencyCode: "MYR",
    symbol: "RM",
  },
  {
    country: "Maldives",
    currency: "Maldivian rufiyaa",
    currencyCode: "MVR",
    symbol: "MRf",
  },
  {
    country: "Mongolia",
    currency: "Mongolian tögrög",
    currencyCode: "MNT",
    symbol: "₮",
  },
  {
    country: "Myanmar",
    currency: "Kyat",
    currencyCode: "MMK",
    symbol: "K",
  },
  {
    country: "Nepal",
    currency: "Nepalese rupee",
    currencyCode: "NPR",
    symbol: "Rs",
  },
  {
    country: "New Zealand",
    currency: "New Zealand dollar",
    currencyCode: "NZD",
    symbol: "$",
  },
  {
    country: "North Korea",
    currency: "North Korean won",
    currencyCode: "KPW",
    symbol: "₩",
  },
  {
    country: "Pakistan",
    currency: "Pakistani rupee",
    currencyCode: "PKR",
    symbol: "Rs",
  },
  {
    country: "Philippines",
    currency: "Philippine peso",
    currencyCode: "PHP",
    symbol: "₱",
  },
  {
    country: "Singapore",
    currency: "Singapore dollar",
    currencyCode: "SGD",
    symbol: "S$",
  },
  {
    country: "South Korea",
    currency: "South Korean won",
    currencyCode: "KRW",
    symbol: "₩",
  },
  {
    country: "Sri Lanka",
    currency: "Sri Lankan rupee",
    currencyCode: "LKR",
    symbol: "Rs",
  },
  {
    country: "Taiwan",
    currency: "New Taiwan dollar",
    currencyCode: "TWD",
    symbol: "NT$",
  },
  {
    country: "Tajikistan",
    currency: "Somoni",
    currencyCode: "TJS",
    symbol: "TJS",
  },
  {
    country: "Timor-Leste",
    currency: "US Dollar",
    currencyCode: "USD",
    symbol: "US$",
  },
  {
    country: "Thailand",
    currency: "Thai baht",
    currencyCode: "THB",
    symbol: "฿",
  },
  {
    country: "Turkmenistan",
    currency: "Turkmen new manat",
    currencyCode: "TMT",
    symbol: "m",
  },
  {
    country: "Uzbekistan",
    currency: "Uzbekistan som",
    currencyCode: "UZS",
    symbol: "som",
  },
  {
    country: "Vietnam",
    currency: "Vietnamese đồng",
    currencyCode: "VND",
    symbol: "₫",
  },
];

export const getCurrencySymbol = (
  code: string,
  defaultSymbol: string = "$",
) => {
  const currency = CURRENCIES.find(
    (c) => c.currencyCode.toUpperCase() === code.toUpperCase(),
  );
  return currency?.symbol || defaultSymbol;
};
