"use client";

import React, { useEffect, useState } from "react";
import { useParams, useRouter } from "next/navigation";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { ImageUpload } from "@/components/admin/ImageUpload";
import { Input } from "@/components/ui/Input";
import apiClient from "@/lib/api/client";
import { slugify } from "@/lib/utils/helpers";
import { toast } from "react-hot-toast";

export default function AdminEditCategoryPage() {
  const params = useParams();
  const router = useRouter();
  const categoryId = params?.id as string;

  const [category, setCategory] = useState<any>(null);
  const [images, setImages] = useState<{ url: string; publicId: string; order: number; alt?: string }[]>([]);
  const [isLoading, setIsLoading] = useState(true);
  const [isSaving, setIsSaving] = useState(false);

  useEffect(() => {
    const loadCategory = async () => {
      try {
        const response = await apiClient.get(`/admin/categories/${categoryId}`);
        const loadedCategory = response.data.data;
        setCategory(loadedCategory);
        setImages(
          loadedCategory.image
            ? [{
                url: loadedCategory.image.url,
                publicId: loadedCategory.image.publicId,
                order: 0,
                alt: loadedCategory.image.alt || "",
              }]
            : [],
        );
      } catch (error: any) {
        toast.error(error?.response?.data?.message || "Unable to load category");
      } finally {
        setIsLoading(false);
      }
    };
    if (categoryId) loadCategory();
  }, [categoryId]);

  const handleSubmit = async (event: React.FormEvent<HTMLFormElement>) => {
    event.preventDefault();
    if (!category?.name) {
      toast.error("Category name is required.");
      return;
    }
    setIsSaving(true);
    try {
      await apiClient.put(`/admin/categories/${categoryId}`, {
        name: category.name,
        slug: slugify(category.name),
        description: category.description || undefined,
        image: images[0]
          ? { url: images[0].url, publicId: images[0].publicId, alt: images[0].alt || undefined }
          : undefined,
        isActive: category.isActive,
      });
      toast.success("Category updated successfully");
      router.push("/admin/categories");
    } catch (error: any) {
      toast.error(error?.response?.data?.message || "Failed to save category");
    } finally {
      setIsSaving(false);
    }
  };

  if (isLoading) {
    return <div className="min-h-[60vh] flex items-center justify-center text-sm text-muted-foreground">Loading category…</div>;
  }

  if (!category) {
    return <div className="min-h-[60vh] flex items-center justify-center text-sm text-error-500">Category not found.</div>;
  }

  return (
    <div className="space-y-8">
      <div>
        <h1 className="text-3xl font-extrabold text-foreground">Edit Category</h1>
        <p className="text-sm text-muted-foreground mt-1">Update category details and visibility.</p>
      </div>

      <Card className="p-6" glass>
        <form className="grid gap-6" onSubmit={handleSubmit}>
          <Input
            label="Name"
            value={category.name || ""}
            onChange={(event) =>
              setCategory({
                ...category,
                name: event.target.value,
                slug: slugify(event.target.value),
              })
            }
            required
          />
          <Input
            label="Slug (autogenerated)"
            value={category.slug || ""}
            disabled
            readOnly
          />
          <label className="flex flex-col gap-2">
            <span className="text-xs font-semibold uppercase tracking-wider text-muted-foreground">
              Description
            </span>
            <textarea
              value={category.description || ""}
              onChange={(event) => setCategory({ ...category, description: event.target.value })}
              className="w-full rounded-lg border border-border bg-input-bg px-4 py-2.5 text-foreground placeholder:text-muted transition-all duration-200 outline-none focus:border-primary-500 focus:ring-4 focus:ring-ring"
              rows={4}
              placeholder="Optional category description"
            />
          </label>
          <ImageUpload
            value={images}
            onChange={setImages}
            folder="categories"
            maxFiles={1}
            label="Category image"
          />
          <Input
            label="Image alt text"
            value={images[0]?.alt || ""}
            onChange={(event) =>
              setImages((prev) =>
                prev.map((img, index) =>
                  index === 0
                    ? { ...img, alt: event.target.value }
                    : img,
                ),
              )
            }
            placeholder="Optional alt text for category image"
          />
          <label className="flex items-center gap-3 text-sm text-muted-foreground">
            <input type="checkbox" checked={category.isActive || false} onChange={(event) => setCategory({ ...category, isActive: event.target.checked })} className="h-4 w-4 rounded border-border text-primary-500" />
            Active
          </label>
          <div className="flex items-center justify-end gap-3 pt-4 border-t border-border">
            <Button variant="secondary" type="button" onClick={() => router.push("/admin/categories")}>Cancel</Button>
            <Button type="submit" isLoading={isSaving}>Save changes</Button>
          </div>
        </form>
      </Card>
    </div>
  );
}
